version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:80"
    command: [ "tail", "-f", "/dev/null" ]
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
